management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
server:
  servlet:
    session:
      timeout: 0
spring:
  main:
    lazy-initialization: true

