management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
server:
  servlet:
    session:
      timeout: 0
  compression:
    enabled: true
spring:
  main:
    lazy-initialization: true
  cloud:
    gcp:
      trace:
        enabled: false
      logging:
        enabled: false