management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  servlet:
    session:
      timeout: 0
  compression:
    enabled: true
spring:
  main:
    lazy-initialization: true
    banner-mode: log
  cloud:
    gcp:
      logging:
        enabled: false
      trace:
        enabled: false
badge:
  github:
    cacheExpireTimeoutSeconds: 60